version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: csa
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - csa-network

  csa-backend:
    image: siyourself/csa-backend:latest
    depends_on:
      - mysql
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/csa?serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - "8081:8081"
    networks:
      - csa-network


networks:
  csa-network:
