version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: csa
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"  # Utilisation du port 3307 sur l'hôte pour éviter le conflit
    networks:
      - csa-network

networks:
  csa-network:
