name: TEST

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout le dépôt
        uses: actions/checkout@v3

      - name: Configuration de Docker Compose et dockerize
        run: |
          sudo apt-get -yqq install docker-compose
          docker-compose --version
          wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz
          tar -xzvf dockerize-linux-amd64-v0.6.1.tar.gz
          sudo mv dockerize /usr/local/bin/dockerize
          dockerize --version

      - name: Démarrer MySQL
        run: docker-compose -f docker-compose-mysql.yml up -d
          
      - name: Attendre 1m30 après le lancement de MySQL
        run: sleep 90

      - name: Afficher les journaux du serveur MySQL
        run: docker-compose -f docker-compose-mysql.yml logs

      - name: Démarrer CSA Backend
        run: docker-compose -f docker-compose-csa.yml up -d

      - name: Attendre que le backend CSA soit prêt
        run: |
          container_name=$(docker-compose -f docker-compose-csa.yml ps -q csa-backend)
          timeout=60
          while [ $timeout -gt 0 ]; do
            logs=$(docker logs $container_name 2>&1)
            echo "$logs"
            sleep 5
            ((timeout-=5))
          done
          echo "Affichage des journaux terminé."

      - name: Exécuter les tests
        run: |
          # Vos commandes de test ici
          echo "Exécution des tests..."

      - name: Arrêter les services
        run: docker-compose -f docker-compose-mysql.yml -f docker-compose-csa.yml down

      - name: Informations de débogage
        run: |
          echo "Contenu du fichier Docker Compose MySQL :"
          cat docker-compose-mysql.yml
          echo "Contenu du fichier Docker Compose CSA Backend :"
          cat docker-compose-csa.yml
          echo "Variables d'environnement :"
          printenv

      - name: Vérifier l'état des services Docker
        run: docker-compose -f docker-compose-mysql.yml -f docker-compose-csa.yml ps
