name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Compose and dockerize
        run: |
          sudo apt-get -yqq install docker-compose
          docker-compose --version
          wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz
          tar -xzvf dockerize-linux-amd64-v0.6.1.tar.gz
          sudo mv dockerize /usr/local/bin/dockerize
          dockerize --version

      - name: Start MySQL and CSA Backend
        run: |
          docker-compose up -d
          docker-compose ps

      - name: Wait for MySQL to be ready
        run: dockerize -wait tcp://localhost:3306 -timeout 1m

      - name: Wait for CSA Backend to be ready
        run: dockerize -wait http://localhost:8081/actuator/health -timeout 1m

      - name: Run Tests
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d '{
            "codeFormation": "L3INFO",
            "diplome": "L",
            "n0Annee": 3,
            "nomFormation": "Licence d'Informatique",
            "doubleDiplome": "N",
            "debutHabilitation": "2012-09-01T00:00:00Z",
            "finHabilitation": "2016-09-01T00:00:00Z"
          }' \
          http://localhost:8081/api/formation/create

      - name: Stop MySQL and CSA Backend
        run: docker-compose down
