name: TEST

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout le dépôt
        uses: actions/checkout@v3

      - name: Configuration de Docker Compose et dockerize
        run: |
          sudo apt-get -yqq install docker-compose
          docker-compose --version
          wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz
          tar -xzvf dockerize-linux-amd64-v0.6.1.tar.gz
          sudo mv dockerize /usr/local/bin/dockerize
          dockerize --version

      - name: Démarrer MySQL
        run: docker-compose -f docker-compose-mysql.yml up -d
          
      - name: Attendre 1m30 après le lancement de MySQL
        run: sleep 30

      - name: Afficher les journaux du serveur MySQL
        run: docker-compose -f docker-compose-mysql.yml logs

      - name: Démarrer CSA Backend
        run: docker-compose -f docker-compose-csa.yml up -d

      - name: Attendre que le backend CSA soit prêt
        run: |
          container_name=$(docker-compose -f docker-compose-csa.yml ps -q csa-backend)
          docker logs $container_name
          sleep 30
          echo "Affichage des journaux terminé."


      
      - name: Exécuter les tests
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d '{
            "codeFormation": "L3INFO",
            "diplome": "L",
            "n0Annee": 3,
            "nomFormation": "Licence d'\''Informatique",
            "doubleDiplome": "N",
            "debutHabilitation": "2012-09-01T00:00:00Z",
            "finHabilitation": "2016-09-01T00:00:00Z"
          }' \
          http://localhost:8081/api/formation/create

      - name: Afficher Table MySQL
        run: |
          # Utilisez la commande docker exec pour exécuter la requête MySQL
          docker exec -i $(docker-compose -f docker-compose-mysql.yml ps -q mysql) mysql -uroot -proot csa -e "SHOW TABLES;"


      - name: Afficher le contenu de la table FORMATION dans MySQL
        run: |
          # Utilisez la commande docker exec pour exécuter la requête MySQL
          docker exec -i $(docker-compose -f docker-compose-mysql.yml ps -q mysql) mysql -uroot -proot csa -e "SELECT * FROM formation;"
      
      - name: Arrêter les services
        run: docker-compose -f docker-compose-mysql.yml -f docker-compose-csa.yml down

      - name: Informations de débogage
        run: |
          echo "Contenu du fichier Docker Compose MySQL :"
          cat docker-compose-mysql.yml
          echo "Contenu du fichier Docker Compose CSA Backend :"
          cat docker-compose-csa.yml
          echo "Variables d'environnement :"
          printenv

      - name: Vérifier l'état des services Docker
        run: docker-compose -f docker-compose-mysql.yml -f docker-compose-csa.yml ps
